version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    restart: always
    ports:
      - "80:80"
    environment:
      - PORT=80
    volumes:
      - ./app:/var/www/app
    command: bash -c "npm install && npm run start"
  e2e:
    build:
      context: .
      dockerfile: ./docker/e2e/Dockerfile
    command: bash -c "npm install && npx cypress run"
    environment:
      - CYPRESS_baseUrl=http://app:80
      - CYPRESS_browser=chrome
    volumes:
      - ./e2e:/var/www/app
    depends_on:
      - app
